// npm imports
import Head from 'next/head'

// local imports
import Board from '@components/Board'

// type imports

export default function Home() {
  return (
    <>
      <Head>
        <title>MOGUL MONEY Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="from-gradientLeft to-gradientRight h-screen w-full bg-gradient-to-r">
        <Board />
      </main>
    </>
  )
}
